/**
 * Location data for autocomplete functionality
 * Includes major ports, cities, warehouses, and logistics hubs worldwide
 */

export interface Location {
  name: string;
  type: 'port' | 'city' | 'warehouse' | 'airport' | 'logistics_hub';
  country: string;
  aliases?: string[];
  coordinates?: {
    lat: number;
    lon: number;
  };
}

export const LOCATIONS_DATABASE: Location[] = [
  // Major Ports
  { name: "Shanghai", type: "port", country: "China", aliases: ["Shanghai Port", "CNSHA"] },
  { name: "Singapore", type: "port", country: "Singapore", aliases: ["Singapore Port", "SGSIN"] },
  { name: "Rotterdam", type: "port", country: "Netherlands", aliases: ["Rotterdam Port", "NLRTM"] },
  { name: "Los Angeles", type: "port", country: "USA", aliases: ["LA", "Los Angeles Port", "USLAX"] },
  { name: "Hamburg", type: "port", country: "Germany", aliases: ["Hamburg Port", "DEHAM"] },
  { name: "Antwerp", type: "port", country: "Belgium", aliases: ["Antwerp Port", "BEANR"] },
  { name: "Hong Kong", type: "port", country: "Hong Kong", aliases: ["Hong Kong Port", "HKHKG"] },
  { name: "Dubai", type: "port", country: "UAE", aliases: ["Dubai Port", "AEDXB", "Jebel Ali"] },
  { name: "Buenaventura", type: "port", country: "Colombia", aliases: ["Buenaventura Port", "COBUN"] },
  { name: "Callao", type: "port", country: "Peru", aliases: ["Callao Port", "PECLL", "Lima Port"] },
  { name: "Long Beach", type: "port", country: "USA", aliases: ["Long Beach Port", "USLGB"] },
  { name: "New York", type: "port", country: "USA", aliases: ["New York Port", "USNYC", "NYC"] },
  { name: "Yokohama", type: "port", country: "Japan", aliases: ["Yokohama Port", "JPYOK"] },
  { name: "Tokyo", type: "port", country: "Japan", aliases: ["Tokyo Port", "JPTYO"] },
  { name: "Cape Town", type: "port", country: "South Africa", aliases: ["Cape Town Port", "ZACPT"] },
  { name: "Durban", type: "port", country: "South Africa", aliases: ["Durban Port", "ZADUR"] },
  { name: "Santos", type: "port", country: "Brazil", aliases: ["Santos Port", "BRSTS"] },
  { name: "Valparaiso", type: "port", country: "Chile", aliases: ["Valparaiso Port", "CLVAP"] },
  { name: "Vancouver", type: "port", country: "Canada", aliases: ["Vancouver Port", "CAVAN"] },
  { name: "Seattle", type: "port", country: "USA", aliases: ["Seattle Port", "USSEA"] },
  { name: "Miami", type: "port", country: "USA", aliases: ["Miami Port", "USMIA"] },
  { name: "Norfolk", type: "port", country: "USA", aliases: ["Norfolk Port", "USNFK"] },
  { name: "Savannah", type: "port", country: "USA", aliases: ["Savannah Port", "USSAV"] },
  { name: "Charleston", type: "port", country: "USA", aliases: ["Charleston Port", "USCHS"] },
  { name: "Le Havre", type: "port", country: "France", aliases: ["Le Havre Port", "FRLEH"] },
  { name: "Marseille", type: "port", country: "France", aliases: ["Marseille Port", "FRMRS"] },
  { name: "Barcelona", type: "port", country: "Spain", aliases: ["Barcelona Port", "ESBCN"] },
  { name: "Valencia", type: "port", country: "Spain", aliases: ["Valencia Port", "ESVLC"] },
  { name: "Genoa", type: "port", country: "Italy", aliases: ["Genoa Port", "ITGOA"] },
  { name: "Naples", type: "port", country: "Italy", aliases: ["Naples Port", "ITNAL"] },
  { name: "Piraeus", type: "port", country: "Greece", aliases: ["Piraeus Port", "GRPIR", "Athens Port"] },
  { name: "Istanbul", type: "port", country: "Turkey", aliases: ["Istanbul Port", "TRIST"] },
  { name: "Vladivostok", type: "port", country: "Russia", aliases: ["Vladivostok Port", "RUVVO"] },
  { name: "Mumbai", type: "port", country: "India", aliases: ["Mumbai Port", "INMAA", "Bombay"] },
  { name: "Chennai", type: "port", country: "India", aliases: ["Chennai Port", "INMAA", "Madras"] },
  { name: "Karachi", type: "port", country: "Pakistan", aliases: ["Karachi Port", "PKKAR"] },
  { name: "Colombo", type: "port", country: "Sri Lanka", aliases: ["Colombo Port", "LKCMB"] },

  // Major Cities
  { name: "London", type: "city", country: "UK", aliases: ["Greater London"] },
  { name: "Paris", type: "city", country: "France", aliases: ["Paris France"] },
  { name: "Berlin", type: "city", country: "Germany", aliases: ["Berlin Germany"] },
  { name: "Madrid", type: "city", country: "Spain", aliases: ["Madrid Spain"] },
  { name: "Rome", type: "city", country: "Italy", aliases: ["Roma"] },
  { name: "Moscow", type: "city", country: "Russia", aliases: ["Moskva"] },
  { name: "Beijing", type: "city", country: "China", aliases: ["Peking"] },
  { name: "Delhi", type: "city", country: "India", aliases: ["New Delhi"] },
  { name: "Bogota", type: "city", country: "Colombia", aliases: ["Bogotá", "Santa Fe de Bogotá"] },
  { name: "Medellín", type: "city", country: "Colombia", aliases: ["Medellin", "Medellín Colombia"] },
  { name: "Cali", type: "city", country: "Colombia", aliases: ["Cali Colombia", "Santiago de Cali"] },
  { name: "Barranquilla", type: "city", country: "Colombia", aliases: ["Barranquilla Colombia"] },
  { name: "Cartagena", type: "city", country: "Colombia", aliases: ["Cartagena Colombia", "Cartagena de Indias"] },
  { name: "Bucaramanga", type: "city", country: "Colombia", aliases: ["Bucaramanga Colombia"] },
  { name: "Pereira", type: "city", country: "Colombia", aliases: ["Pereira Colombia"] },
  { name: "Manizales", type: "city", country: "Colombia", aliases: ["Manizales Colombia"] },
  { name: "Pasto", type: "city", country: "Colombia", aliases: ["Pasto Colombia"] },
  { name: "Neiva", type: "city", country: "Colombia", aliases: ["Neiva Colombia"] },
  { name: "Ibagué", type: "city", country: "Colombia", aliases: ["Ibague", "Ibagué Colombia"] },
  { name: "Montería", type: "city", country: "Colombia", aliases: ["Monteria", "Montería Colombia"] },
  { name: "Villavicencio", type: "city", country: "Colombia", aliases: ["Villavicencio Colombia"] },
  { name: "Lima", type: "city", country: "Peru", aliases: ["Lima Peru"] },
  { name: "Arequipa", type: "city", country: "Peru", aliases: ["Arequipa Peru"] },
  { name: "Trujillo", type: "city", country: "Peru", aliases: ["Trujillo Peru"] },
  { name: "Chiclayo", type: "city", country: "Peru", aliases: ["Chiclayo Peru"] },
  { name: "Piura", type: "city", country: "Peru", aliases: ["Piura Peru"] },
  { name: "Iquitos", type: "city", country: "Peru", aliases: ["Iquitos Peru"] },
  { name: "Cusco", type: "city", country: "Peru", aliases: ["Cuzco", "Cusco Peru"] },
  { name: "Mexico City", type: "city", country: "Mexico", aliases: ["CDMX", "Ciudad de México"] },
  { name: "Guadalajara", type: "city", country: "Mexico", aliases: ["Guadalajara Mexico"] },
  { name: "Monterrey", type: "city", country: "Mexico", aliases: ["Monterrey Mexico"] },
  { name: "Tijuana", type: "city", country: "Mexico", aliases: ["Tijuana Mexico"] },
  { name: "Puebla", type: "city", country: "Mexico", aliases: ["Puebla Mexico"] },
  { name: "Juárez", type: "city", country: "Mexico", aliases: ["Ciudad Juárez", "Juarez"] },
  { name: "León", type: "city", country: "Mexico", aliases: ["León Mexico"] },
  { name: "Zapopan", type: "city", country: "Mexico", aliases: ["Zapopan Mexico"] },
  { name: "Mérida", type: "city", country: "Mexico", aliases: ["Merida Mexico"] },
  { name: "San Luis Potosí", type: "city", country: "Mexico", aliases: ["San Luis Potosi"] },
  { name: "São Paulo", type: "city", country: "Brazil", aliases: ["Sao Paulo"] },
  { name: "Rio de Janeiro", type: "city", country: "Brazil", aliases: ["Rio", "Rio de Janeiro Brazil"] },
  { name: "Brasília", type: "city", country: "Brazil", aliases: ["Brasilia"] },
  { name: "Salvador", type: "city", country: "Brazil", aliases: ["Salvador Brazil"] },
  { name: "Fortaleza", type: "city", country: "Brazil", aliases: ["Fortaleza Brazil"] },
  { name: "Belo Horizonte", type: "city", country: "Brazil", aliases: ["Belo Horizonte Brazil"] },
  { name: "Manaus", type: "city", country: "Brazil", aliases: ["Manaus Brazil"] },
  { name: "Curitiba", type: "city", country: "Brazil", aliases: ["Curitiba Brazil"] },
  { name: "Recife", type: "city", country: "Brazil", aliases: ["Recife Brazil"] },
  { name: "Porto Alegre", type: "city", country: "Brazil", aliases: ["Porto Alegre Brazil"] },
  { name: "Belém", type: "city", country: "Brazil", aliases: ["Belem Brazil"] },
  { name: "Goiânia", type: "city", country: "Brazil", aliases: ["Goiania Brazil"] },
  { name: "Campinas", type: "city", country: "Brazil", aliases: ["Campinas Brazil"] },
  { name: "Buenos Aires", type: "city", country: "Argentina", aliases: ["CABA"] },
  { name: "Córdoba", type: "city", country: "Argentina", aliases: ["Cordoba Argentina"] },
  { name: "Rosario", type: "city", country: "Argentina", aliases: ["Rosario Argentina"] },
  { name: "Mendoza", type: "city", country: "Argentina", aliases: ["Mendoza Argentina"] },
  { name: "Tucumán", type: "city", country: "Argentina", aliases: ["Tucuman Argentina"] },
  { name: "La Plata", type: "city", country: "Argentina", aliases: ["La Plata Argentina"] },
  { name: "Mar del Plata", type: "city", country: "Argentina", aliases: ["Mar del Plata Argentina"] },
  { name: "Santiago", type: "city", country: "Chile", aliases: ["Santiago Chile"] },
  { name: "Valparaíso", type: "city", country: "Chile", aliases: ["Valparaiso Chile"] },
  { name: "Concepción", type: "city", country: "Chile", aliases: ["Concepcion Chile"] },
  { name: "La Serena", type: "city", country: "Chile", aliases: ["La Serena Chile"] },
  { name: "Antofagasta", type: "city", country: "Chile", aliases: ["Antofagasta Chile"] },
  { name: "Temuco", type: "city", country: "Chile", aliases: ["Temuco Chile"] },
  { name: "Iquique", type: "city", country: "Chile", aliases: ["Iquique Chile"] },
  { name: "Caracas", type: "city", country: "Venezuela", aliases: ["Caracas Venezuela"] },
  { name: "Maracaibo", type: "city", country: "Venezuela", aliases: ["Maracaibo Venezuela"] },
  { name: "Valencia", type: "city", country: "Venezuela", aliases: ["Valencia Venezuela"] },
  { name: "Barquisimeto", type: "city", country: "Venezuela", aliases: ["Barquisimeto Venezuela"] },
  { name: "Maracay", type: "city", country: "Venezuela", aliases: ["Maracay Venezuela"] },
  { name: "Quito", type: "city", country: "Ecuador", aliases: ["Quito Ecuador"] },
  { name: "Guayaquil", type: "city", country: "Ecuador", aliases: ["Guayaquil Ecuador"] },
  { name: "Cuenca", type: "city", country: "Ecuador", aliases: ["Cuenca Ecuador"] },
  { name: "Ambato", type: "city", country: "Ecuador", aliases: ["Ambato Ecuador"] },
  { name: "Manta", type: "city", country: "Ecuador", aliases: ["Manta Ecuador"] },
  { name: "La Paz", type: "city", country: "Bolivia", aliases: ["La Paz Bolivia"] },
  { name: "Santa Cruz", type: "city", country: "Bolivia", aliases: ["Santa Cruz Bolivia"] },
  { name: "Cochabamba", type: "city", country: "Bolivia", aliases: ["Cochabamba Bolivia"] },
  { name: "Sucre", type: "city", country: "Bolivia", aliases: ["Sucre Bolivia"] },
  { name: "Asunción", type: "city", country: "Paraguay", aliases: ["Asuncion Paraguay"] },
  { name: "Ciudad del Este", type: "city", country: "Paraguay", aliases: ["Ciudad del Este Paraguay"] },
  { name: "Montevideo", type: "city", country: "Uruguay", aliases: ["Montevideo Uruguay"] },
  { name: "Punta del Este", type: "city", country: "Uruguay", aliases: ["Punta del Este Uruguay"] },
  { name: "Georgetown", type: "city", country: "Guyana", aliases: ["Georgetown Guyana"] },
  { name: "Paramaribo", type: "city", country: "Suriname", aliases: ["Paramaribo Suriname"] },
  { name: "Cayenne", type: "city", country: "French Guiana", aliases: ["Cayenne French Guiana"] },
  { name: "Toronto", type: "city", country: "Canada", aliases: ["Toronto Canada"] },
  { name: "Montreal", type: "city", country: "Canada", aliases: ["Montréal"] },
  { name: "Vancouver", type: "city", country: "Canada", aliases: ["Vancouver Canada"] },
  { name: "Calgary", type: "city", country: "Canada", aliases: ["Calgary Canada"] },
  { name: "Edmonton", type: "city", country: "Canada", aliases: ["Edmonton Canada"] },
  { name: "Ottawa", type: "city", country: "Canada", aliases: ["Ottawa Canada"] },
  { name: "Winnipeg", type: "city", country: "Canada", aliases: ["Winnipeg Canada"] },
  { name: "Quebec City", type: "city", country: "Canada", aliases: ["Quebec", "Québec"] },
  { name: "Hamilton", type: "city", country: "Canada", aliases: ["Hamilton Canada"] },
  { name: "Kitchener", type: "city", country: "Canada", aliases: ["Kitchener Canada"] },
  { name: "London", type: "city", country: "Canada", aliases: ["London Canada"] },
  { name: "Halifax", type: "city", country: "Canada", aliases: ["Halifax Canada"] },
  { name: "Chicago", type: "city", country: "USA", aliases: ["Chicago IL"] },
  { name: "Houston", type: "city", country: "USA", aliases: ["Houston TX"] },
  { name: "Denver", type: "city", country: "USA", aliases: ["Denver CO"] },
  { name: "Atlanta", type: "city", country: "USA", aliases: ["Atlanta GA"] },
  { name: "Salt Lake City", type: "city", country: "USA", aliases: ["SLC", "Salt Lake"] },
  { name: "Phoenix", type: "city", country: "USA", aliases: ["Phoenix AZ"] },
  { name: "Las Vegas", type: "city", country: "USA", aliases: ["Vegas", "Las Vegas NV"] },
  { name: "San Francisco", type: "city", country: "USA", aliases: ["SF", "San Francisco CA"] },
  { name: "Portland", type: "city", country: "USA", aliases: ["Portland OR"] },
  { name: "Boston", type: "city", country: "USA", aliases: ["Boston MA"] },
  { name: "Philadelphia", type: "city", country: "USA", aliases: ["Philly", "Philadelphia PA"] },
  { name: "Detroit", type: "city", country: "USA", aliases: ["Detroit MI"] },
  { name: "Minneapolis", type: "city", country: "USA", aliases: ["Minneapolis MN", "Twin Cities"] },
  { name: "Dallas", type: "city", country: "USA", aliases: ["Dallas TX"] },
  { name: "Memphis", type: "city", country: "USA", aliases: ["Memphis TN"] },
  { name: "Nashville", type: "city", country: "USA", aliases: ["Nashville TN"] },
  { name: "Kansas City", type: "city", country: "USA", aliases: ["KC", "Kansas City MO"] },
  { name: "St. Louis", type: "city", country: "USA", aliases: ["Saint Louis", "St Louis MO"] },
  { name: "Cincinnati", type: "city", country: "USA", aliases: ["Cincinnati OH"] },
  { name: "Columbus", type: "city", country: "USA", aliases: ["Columbus OH"] },
  { name: "Cleveland", type: "city", country: "USA", aliases: ["Cleveland OH"] },
  { name: "Pittsburgh", type: "city", country: "USA", aliases: ["Pittsburgh PA"] },
  { name: "Indianapolis", type: "city", country: "USA", aliases: ["Indy", "Indianapolis IN"] },
  { name: "Milwaukee", type: "city", country: "USA", aliases: ["Milwaukee WI"] },
  { name: "San Diego", type: "city", country: "USA", aliases: ["San Diego CA"] },
  { name: "San Antonio", type: "city", country: "USA", aliases: ["San Antonio TX"] },
  { name: "Austin", type: "city", country: "USA", aliases: ["Austin TX"] },
  { name: "Fort Worth", type: "city", country: "USA", aliases: ["Fort Worth TX"] },
  { name: "Charlotte", type: "city", country: "USA", aliases: ["Charlotte NC"] },
  { name: "Jacksonville", type: "city", country: "USA", aliases: ["Jacksonville FL"] },
  { name: "Indianapolis", type: "city", country: "USA", aliases: ["Indianapolis IN"] },
  { name: "San Jose", type: "city", country: "USA", aliases: ["San Jose CA"] },
  { name: "Madrid", type: "city", country: "Spain", aliases: ["Madrid España"] },
  { name: "Barcelona", type: "city", country: "Spain", aliases: ["Barcelona España"] },
  { name: "Valencia", type: "city", country: "Spain", aliases: ["Valencia España"] },
  { name: "Seville", type: "city", country: "Spain", aliases: ["Sevilla"] },
  { name: "Zaragoza", type: "city", country: "Spain", aliases: ["Zaragoza España"] },
  { name: "Málaga", type: "city", country: "Spain", aliases: ["Malaga"] },
  { name: "Murcia", type: "city", country: "Spain", aliases: ["Murcia España"] },
  { name: "Palma", type: "city", country: "Spain", aliases: ["Palma de Mallorca"] },
  { name: "Las Palmas", type: "city", country: "Spain", aliases: ["Las Palmas de Gran Canaria"] },
  { name: "Bilbao", type: "city", country: "Spain", aliases: ["Bilbao España"] },

  // Asian Cities
  { name: "Tokyo", type: "city", country: "Japan", aliases: ["Tokyo Japan"] },
  { name: "Osaka", type: "city", country: "Japan", aliases: ["Osaka Japan"] },
  { name: "Kyoto", type: "city", country: "Japan", aliases: ["Kyoto Japan"] },
  { name: "Nagoya", type: "city", country: "Japan", aliases: ["Nagoya Japan"] },
  { name: "Fukuoka", type: "city", country: "Japan", aliases: ["Fukuoka Japan"] },
  { name: "Sendai", type: "city", country: "Japan", aliases: ["Sendai Japan"] },
  { name: "Hiroshima", type: "city", country: "Japan", aliases: ["Hiroshima Japan"] },
  { name: "Seoul", type: "city", country: "South Korea", aliases: ["Seoul Korea"] },
  { name: "Busan", type: "city", country: "South Korea", aliases: ["Pusan"] },
  { name: "Incheon", type: "city", country: "South Korea", aliases: ["Incheon Korea"] },
  { name: "Daegu", type: "city", country: "South Korea", aliases: ["Daegu Korea"] },
  { name: "Daejeon", type: "city", country: "South Korea", aliases: ["Daejeon Korea"] },
  { name: "Gwangju", type: "city", country: "South Korea", aliases: ["Gwangju Korea"] },
  { name: "Beijing", type: "city", country: "China", aliases: ["Peking", "Beijing China"] },
  { name: "Shanghai", type: "city", country: "China", aliases: ["Shanghai China"] },
  { name: "Guangzhou", type: "city", country: "China", aliases: ["Canton"] },
  { name: "Shenzhen", type: "city", country: "China", aliases: ["Shenzhen China"] },
  { name: "Chengdu", type: "city", country: "China", aliases: ["Chengdu China"] },
  { name: "Hangzhou", type: "city", country: "China", aliases: ["Hangzhou China"] },
  { name: "Wuhan", type: "city", country: "China", aliases: ["Wuhan China"] },
  { name: "Xi'an", type: "city", country: "China", aliases: ["Xian", "Xi'an China"] },
  { name: "Chongqing", type: "city", country: "China", aliases: ["Chongqing China"] },
  { name: "Tianjin", type: "city", country: "China", aliases: ["Tianjin China"] },
  { name: "Nanjing", type: "city", country: "China", aliases: ["Nanking"] },
  { name: "Shenyang", type: "city", country: "China", aliases: ["Shenyang China"] },
  { name: "Harbin", type: "city", country: "China", aliases: ["Harbin China"] },
  { name: "Dalian", type: "city", country: "China", aliases: ["Dalian China"] },
  { name: "Qingdao", type: "city", country: "China", aliases: ["Tsingtao"] },
  { name: "Ningbo", type: "city", country: "China", aliases: ["Ningbo China"] },
  { name: "Xiamen", type: "city", country: "China", aliases: ["Amoy"] },
  { name: "Mumbai", type: "city", country: "India", aliases: ["Bombay"] },
  { name: "Delhi", type: "city", country: "India", aliases: ["New Delhi"] },
  { name: "Bangalore", type: "city", country: "India", aliases: ["Bengaluru"] },
  { name: "Hyderabad", type: "city", country: "India", aliases: ["Hyderabad India"] },
  { name: "Chennai", type: "city", country: "India", aliases: ["Madras"] },
  { name: "Kolkata", type: "city", country: "India", aliases: ["Calcutta"] },
  { name: "Pune", type: "city", country: "India", aliases: ["Pune India"] },
  { name: "Ahmedabad", type: "city", country: "India", aliases: ["Ahmedabad India"] },
  { name: "Jaipur", type: "city", country: "India", aliases: ["Jaipur India"] },
  { name: "Surat", type: "city", country: "India", aliases: ["Surat India"] },
  { name: "Lucknow", type: "city", country: "India", aliases: ["Lucknow India"] },
  { name: "Kanpur", type: "city", country: "India", aliases: ["Kanpur India"] },
  { name: "Nagpur", type: "city", country: "India", aliases: ["Nagpur India"] },
  { name: "Indore", type: "city", country: "India", aliases: ["Indore India"] },
  { name: "Bhopal", type: "city", country: "India", aliases: ["Bhopal India"] },
  { name: "Visakhapatnam", type: "city", country: "India", aliases: ["Vizag"] },
  { name: "Pimpri-Chinchwad", type: "city", country: "India", aliases: ["Pimpri Chinchwad"] },
  { name: "Patna", type: "city", country: "India", aliases: ["Patna India"] },
  { name: "Vadodara", type: "city", country: "India", aliases: ["Baroda"] },
  { name: "Ludhiana", type: "city", country: "India", aliases: ["Ludhiana India"] },
  { name: "Agra", type: "city", country: "India", aliases: ["Agra India"] },
  { name: "Nashik", type: "city", country: "India", aliases: ["Nashik India"] },
  { name: "Faridabad", type: "city", country: "India", aliases: ["Faridabad India"] },
  { name: "Meerut", type: "city", country: "India", aliases: ["Meerut India"] },
  { name: "Rajkot", type: "city", country: "India", aliases: ["Rajkot India"] },
  { name: "Kalyan-Dombivli", type: "city", country: "India", aliases: ["Kalyan Dombivli"] },
  { name: "Vasai-Virar", type: "city", country: "India", aliases: ["Vasai Virar"] },
  { name: "Varanasi", type: "city", country: "India", aliases: ["Benares", "Kashi"] },
  { name: "Srinagar", type: "city", country: "India", aliases: ["Srinagar India"] },
  { name: "Aurangabad", type: "city", country: "India", aliases: ["Aurangabad India"] },
  { name: "Dhanbad", type: "city", country: "India", aliases: ["Dhanbad India"] },
  { name: "Amritsar", type: "city", country: "India", aliases: ["Amritsar India"] },
  { name: "Navi Mumbai", type: "city", country: "India", aliases: ["New Mumbai"] },
  { name: "Allahabad", type: "city", country: "India", aliases: ["Prayagraj"] },
  { name: "Ranchi", type: "city", country: "India", aliases: ["Ranchi India"] },
  { name: "Howrah", type: "city", country: "India", aliases: ["Howrah India"] },
  { name: "Coimbatore", type: "city", country: "India", aliases: ["Coimbatore India"] },
  { name: "Jabalpur", type: "city", country: "India", aliases: ["Jabalpur India"] },
  { name: "Gwalior", type: "city", country: "India", aliases: ["Gwalior India"] },
  { name: "Vijayawada", type: "city", country: "India", aliases: ["Vijayawada India"] },
  { name: "Jodhpur", type: "city", country: "India", aliases: ["Jodhpur India"] },
  { name: "Madurai", type: "city", country: "India", aliases: ["Madurai India"] },
  { name: "Raipur", type: "city", country: "India", aliases: ["Raipur India"] },
  { name: "Kota", type: "city", country: "India", aliases: ["Kota India"] },
  { name: "Guwahati", type: "city", country: "India", aliases: ["Guwahati India"] },
  { name: "Chandigarh", type: "city", country: "India", aliases: ["Chandigarh India"] },
  { name: "Thiruvananthapuram", type: "city", country: "India", aliases: ["Trivandrum"] },
  { name: "Solapur", type: "city", country: "India", aliases: ["Solapur India"] },
  { name: "Hubballi-Dharwad", type: "city", country: "India", aliases: ["Hubli Dharwad"] },
  { name: "Tiruchirappalli", type: "city", country: "India", aliases: ["Trichy"] },
  { name: "Bareilly", type: "city", country: "India", aliases: ["Bareilly India"] },
  { name: "Mysore", type: "city", country: "India", aliases: ["Mysuru"] },
  { name: "Tiruppur", type: "city", country: "India", aliases: ["Tiruppur India"] },
  { name: "Gurgaon", type: "city", country: "India", aliases: ["Gurugram"] },
  { name: "Aligarh", type: "city", country: "India", aliases: ["Aligarh India"] },
  { name: "Jalandhar", type: "city", country: "India", aliases: ["Jalandhar India"] },
  { name: "Bhubaneswar", type: "city", country: "India", aliases: ["Bhubaneswar India"] },
  { name: "Salem", type: "city", country: "India", aliases: ["Salem India"] },
  { name: "Warangal", type: "city", country: "India", aliases: ["Warangal India"] },
  { name: "Guntur", type: "city", country: "India", aliases: ["Guntur India"] },
  { name: "Bhiwandi", type: "city", country: "India", aliases: ["Bhiwandi India"] },
  { name: "Saharanpur", type: "city", country: "India", aliases: ["Saharanpur India"] },
  { name: "Gorakhpur", type: "city", country: "India", aliases: ["Gorakhpur India"] },
  { name: "Bikaner", type: "city", country: "India", aliases: ["Bikaner India"] },
  { name: "Amravati", type: "city", country: "India", aliases: ["Amravati India"] },
  { name: "Noida", type: "city", country: "India", aliases: ["Noida India"] },
  { name: "Jamshedpur", type: "city", country: "India", aliases: ["Jamshedpur India"] },
  { name: "Bhilai Nagar", type: "city", country: "India", aliases: ["Bhilai"] },
  { name: "Cuttack", type: "city", country: "India", aliases: ["Cuttack India"] },
  { name: "Firozabad", type: "city", country: "India", aliases: ["Firozabad India"] },
  { name: "Kochi", type: "city", country: "India", aliases: ["Cochin"] },
  { name: "Bhavnagar", type: "city", country: "India", aliases: ["Bhavnagar India"] },
  { name: "Dehradun", type: "city", country: "India", aliases: ["Dehradun India"] },
  { name: "Durgapur", type: "city", country: "India", aliases: ["Durgapur India"] },
  { name: "Asansol", type: "city", country: "India", aliases: ["Asansol India"] },
  { name: "Nanded Waghala", type: "city", country: "India", aliases: ["Nanded"] },
  { name: "Kolhapur", type: "city", country: "India", aliases: ["Kolhapur India"] },
  { name: "Ajmer", type: "city", country: "India", aliases: ["Ajmer India"] },
  { name: "Gulbarga", type: "city", country: "India", aliases: ["Kalaburagi"] },
  { name: "Jamnagar", type: "city", country: "India", aliases: ["Jamnagar India"] },
  { name: "Ujjain", type: "city", country: "India", aliases: ["Ujjain India"] },
  { name: "Loni", type: "city", country: "India", aliases: ["Loni India"] },
  { name: "Siliguri", type: "city", country: "India", aliases: ["Siliguri India"] },
  { name: "Jhansi", type: "city", country: "India", aliases: ["Jhansi India"] },
  { name: "Ulhasnagar", type: "city", country: "India", aliases: ["Ulhasnagar India"] },
  { name: "Nellore", type: "city", country: "India", aliases: ["Nellore India"] },
  { name: "Jammu", type: "city", country: "India", aliases: ["Jammu India"] },
  { name: "Sangli-Miraj & Kupwad", type: "city", country: "India", aliases: ["Sangli"] },
  { name: "Belgaum", type: "city", country: "India", aliases: ["Belagavi"] },
  { name: "Mangalore", type: "city", country: "India", aliases: ["Mangaluru"] },
  { name: "Ambattur", type: "city", country: "India", aliases: ["Ambattur India"] },
  { name: "Tirunelveli", type: "city", country: "India", aliases: ["Tirunelveli India"] },
  { name: "Malegaon", type: "city", country: "India", aliases: ["Malegaon India"] },
  { name: "Gaya", type: "city", country: "India", aliases: ["Gaya India"] },
  { name: "Jalgaon", type: "city", country: "India", aliases: ["Jalgaon India"] },
  { name: "Udaipur", type: "city", country: "India", aliases: ["Udaipur India"] },
  { name: "Maheshtala", type: "city", country: "India", aliases: ["Maheshtala India"] },
  { name: "Jakarta", type: "city", country: "Indonesia", aliases: ["Jakarta Indonesia"] },
  { name: "Surabaya", type: "city", country: "Indonesia", aliases: ["Surabaya Indonesia"] },
  { name: "Bandung", type: "city", country: "Indonesia", aliases: ["Bandung Indonesia"] },
  { name: "Medan", type: "city", country: "Indonesia", aliases: ["Medan Indonesia"] },
  { name: "Semarang", type: "city", country: "Indonesia", aliases: ["Semarang Indonesia"] },
  { name: "Makassar", type: "city", country: "Indonesia", aliases: ["Makassar Indonesia"] },
  { name: "Palembang", type: "city", country: "Indonesia", aliases: ["Palembang Indonesia"] },
  { name: "Tangerang", type: "city", country: "Indonesia", aliases: ["Tangerang Indonesia"] },
  { name: "South Tangerang", type: "city", country: "Indonesia", aliases: ["Tangerang Selatan"] },
  { name: "Depok", type: "city", country: "Indonesia", aliases: ["Depok Indonesia"] },
  { name: "Padang", type: "city", country: "Indonesia", aliases: ["Padang Indonesia"] },
  { name: "Denpasar", type: "city", country: "Indonesia", aliases: ["Denpasar Indonesia"] },
  { name: "Samarinda", type: "city", country: "Indonesia", aliases: ["Samarinda Indonesia"] },
  { name: "Bandar Lampung", type: "city", country: "Indonesia", aliases: ["Bandar Lampung Indonesia"] },
  { name: "Bekasi", type: "city", country: "Indonesia", aliases: ["Bekasi Indonesia"] },
  { name: "Balikpapan", type: "city", country: "Indonesia", aliases: ["Balikpapan Indonesia"] },
  { name: "Jambi", type: "city", country: "Indonesia", aliases: ["Jambi Indonesia"] },
  { name: "Pekanbaru", type: "city", country: "Indonesia", aliases: ["Pekanbaru Indonesia"] },
  { name: "Batam", type: "city", country: "Indonesia", aliases: ["Batam Indonesia"] },
  { name: "Banjarmasin", type: "city", country: "Indonesia", aliases: ["Banjarmasin Indonesia"] },
  { name: "Malang", type: "city", country: "Indonesia", aliases: ["Malang Indonesia"] },
  { name: "Yogyakarta", type: "city", country: "Indonesia", aliases: ["Jogja", "Yogya"] },
  { name: "Pontianak", type: "city", country: "Indonesia", aliases: ["Pontianak Indonesia"] },
  { name: "Bogor", type: "city", country: "Indonesia", aliases: ["Bogor Indonesia"] },
  { name: "Manado", type: "city", country: "Indonesia", aliases: ["Manado Indonesia"] },
  { name: "Mataram", type: "city", country: "Indonesia", aliases: ["Mataram Indonesia"] },
  { name: "Kupang", type: "city", country: "Indonesia", aliases: ["Kupang Indonesia"] },
  { name: "Bangkok", type: "city", country: "Thailand", aliases: ["Bangkok Thailand"] },
  { name: "Nonthaburi", type: "city", country: "Thailand", aliases: ["Nonthaburi Thailand"] },
  { name: "Nakhon Ratchasima", type: "city", country: "Thailand", aliases: ["Korat"] },
  { name: "Chiang Mai", type: "city", country: "Thailand", aliases: ["Chiang Mai Thailand"] },
  { name: "Hat Yai", type: "city", country: "Thailand", aliases: ["Hat Yai Thailand"] },
  { name: "Udon Thani", type: "city", country: "Thailand", aliases: ["Udon Thani Thailand"] },
  { name: "Pak Kret", type: "city", country: "Thailand", aliases: ["Pak Kret Thailand"] },
  { name: "Khon Kaen", type: "city", country: "Thailand", aliases: ["Khon Kaen Thailand"] },
  { name: "Nakhon Si Thammarat", type: "city", country: "Thailand", aliases: ["Nakhon Si Thammarat Thailand"] },
  { name: "Rayong", type: "city", country: "Thailand", aliases: ["Rayong Thailand"] },
  { name: "Chon Buri", type: "city", country: "Thailand", aliases: ["Chon Buri Thailand"] },
  { name: "Lampang", type: "city", country: "Thailand", aliases: ["Lampang Thailand"] },
  { name: "Surat Thani", type: "city", country: "Thailand", aliases: ["Surat Thani Thailand"] },
  { name: "Phuket", type: "city", country: "Thailand", aliases: ["Phuket Thailand"] },
  { name: "Nakhon Pathom", type: "city", country: "Thailand", aliases: ["Nakhon Pathom Thailand"] },
  { name: "Samut Prakan", type: "city", country: "Thailand", aliases: ["Samut Prakan Thailand"] },
  { name: "Kuala Lumpur", type: "city", country: "Malaysia", aliases: ["KL"] },
  { name: "George Town", type: "city", country: "Malaysia", aliases: ["Penang"] },
  { name: "Ipoh", type: "city", country: "Malaysia", aliases: ["Ipoh Malaysia"] },
  { name: "Shah Alam", type: "city", country: "Malaysia", aliases: ["Shah Alam Malaysia"] },
  { name: "Petaling Jaya", type: "city", country: "Malaysia", aliases: ["PJ"] },
  { name: "Johor Bahru", type: "city", country: "Malaysia", aliases: ["JB"] },
  { name: "Subang Jaya", type: "city", country: "Malaysia", aliases: ["Subang Jaya Malaysia"] },
  { name: "Kota Kinabalu", type: "city", country: "Malaysia", aliases: ["KK"] },
  { name: "Klang", type: "city", country: "Malaysia", aliases: ["Klang Malaysia"] },
  { name: "Kajang", type: "city", country: "Malaysia", aliases: ["Kajang Malaysia"] },
  { name: "Seremban", type: "city", country: "Malaysia", aliases: ["Seremban Malaysia"] },
  { name: "Petaling", type: "city", country: "Malaysia", aliases: ["Petaling Malaysia"] },
  { name: "Iskandar Puteri", type: "city", country: "Malaysia", aliases: ["Nusajaya"] },
  { name: "Kuantan", type: "city", country: "Malaysia", aliases: ["Kuantan Malaysia"] },
  { name: "Selayang", type: "city", country: "Malaysia", aliases: ["Selayang Malaysia"] },
  { name: "Ampang Jaya", type: "city", country: "Malaysia", aliases: ["Ampang"] },
  { name: "Malacca City", type: "city", country: "Malaysia", aliases: ["Melaka"] },
  { name: "Alorsetar", type: "city", country: "Malaysia", aliases: ["Alor Setar"] },
  { name: "Miri", type: "city", country: "Malaysia", aliases: ["Miri Malaysia"] },
  { name: "Kulim", type: "city", country: "Malaysia", aliases: ["Kulim Malaysia"] },
  { name: "Kota Bharu", type: "city", country: "Malaysia", aliases: ["Kota Bharu Malaysia"] },
  { name: "Kuala Terengganu", type: "city", country: "Malaysia", aliases: ["Kuala Terengganu Malaysia"] },
  { name: "Singapore", type: "city", country: "Singapore", aliases: ["Singapore City"] },
  { name: "Manila", type: "city", country: "Philippines", aliases: ["Manila Philippines"] },
  { name: "Quezon City", type: "city", country: "Philippines", aliases: ["QC"] },
  { name: "Caloocan", type: "city", country: "Philippines", aliases: ["Caloocan Philippines"] },
  { name: "Davao City", type: "city", country: "Philippines", aliases: ["Davao"] },
  { name: "Cebu City", type: "city", country: "Philippines", aliases: ["Cebu"] },
  { name: "Zamboanga City", type: "city", country: "Philippines", aliases: ["Zamboanga"] },
  { name: "Antipolo", type: "city", country: "Philippines", aliases: ["Antipolo Philippines"] },
  { name: "Pasig", type: "city", country: "Philippines", aliases: ["Pasig Philippines"] },
  { name: "Taguig", type: "city", country: "Philippines", aliases: ["Taguig Philippines"] },
  { name: "Cagayan de Oro", type: "city", country: "Philippines", aliases: ["CDO"] },
  { name: "Paranaque", type: "city", country: "Philippines", aliases: ["Paranaque Philippines"] },
  { name: "Valenzuela", type: "city", country: "Philippines", aliases: ["Valenzuela Philippines"] },
  { name: "Dasmariñas", type: "city", country: "Philippines", aliases: ["Dasmarinas"] },
  { name: "Las Piñas", type: "city", country: "Philippines", aliases: ["Las Pinas"] },
  { name: "Makati", type: "city", country: "Philippines", aliases: ["Makati Philippines"] },
  { name: "Mandaluyong", type: "city", country: "Philippines", aliases: ["Mandaluyong Philippines"] },
  { name: "Marikina", type: "city", country: "Philippines", aliases: ["Marikina Philippines"] },
  { name: "Muntinlupa", type: "city", country: "Philippines", aliases: ["Muntinlupa Philippines"] },
  { name: "San Jose del Monte", type: "city", country: "Philippines", aliases: ["San Jose del Monte Philippines"] },
  { name: "Bacoor", type: "city", country: "Philippines", aliases: ["Bacoor Philippines"] },
  { name: "Iloilo City", type: "city", country: "Philippines", aliases: ["Iloilo"] },
  { name: "General Santos", type: "city", country: "Philippines", aliases: ["GenSan"] },
  { name: "Bacolod", type: "city", country: "Philippines", aliases: ["Bacolod Philippines"] },
  { name: "Baguio", type: "city", country: "Philippines", aliases: ["Baguio Philippines"] },
  { name: "Hanoi", type: "city", country: "Vietnam", aliases: ["Hanoi Vietnam"] },
  { name: "Ho Chi Minh City", type: "city", country: "Vietnam", aliases: ["Saigon", "HCMC"] },
  { name: "Haiphong", type: "city", country: "Vietnam", aliases: ["Haiphong Vietnam"] },
  { name: "Can Tho", type: "city", country: "Vietnam", aliases: ["Can Tho Vietnam"] },
  { name: "Da Nang", type: "city", country: "Vietnam", aliases: ["Danang"] },
  { name: "Bien Hoa", type: "city", country: "Vietnam", aliases: ["Bien Hoa Vietnam"] },
  { name: "Hue", type: "city", country: "Vietnam", aliases: ["Hue Vietnam"] },
  { name: "Nha Trang", type: "city", country: "Vietnam", aliases: ["Nha Trang Vietnam"] },
  { name: "Buon Ma Thuot", type: "city", country: "Vietnam", aliases: ["Buon Ma Thuot Vietnam"] },
  { name: "Vung Tau", type: "city", country: "Vietnam", aliases: ["Vung Tau Vietnam"] },
  { name: "Nam Dinh", type: "city", country: "Vietnam", aliases: ["Nam Dinh Vietnam"] },
  { name: "Quy Nhon", type: "city", country: "Vietnam", aliases: ["Quy Nhon Vietnam"] },
  { name: "Thai Nguyen", type: "city", country: "Vietnam", aliases: ["Thai Nguyen Vietnam"] },
  { name: "Thanh Hoa", type: "city", country: "Vietnam", aliases: ["Thanh Hoa Vietnam"] },
  { name: "Rach Gia", type: "city", country: "Vietnam", aliases: ["Rach Gia Vietnam"] },
  { name: "Cam Ranh", type: "city", country: "Vietnam", aliases: ["Cam Ranh Vietnam"] },
  { name: "Phnom Penh", type: "city", country: "Cambodia", aliases: ["Phnom Penh Cambodia"] },
  { name: "Siem Reap", type: "city", country: "Cambodia", aliases: ["Siem Reap Cambodia"] },
  { name: "Battambang", type: "city", country: "Cambodia", aliases: ["Battambang Cambodia"] },
  { name: "Sihanoukville", type: "city", country: "Cambodia", aliases: ["Sihanoukville Cambodia"] },
  { name: "Vientiane", type: "city", country: "Laos", aliases: ["Vientiane Laos"] },
  { name: "Pakse", type: "city", country: "Laos", aliases: ["Pakse Laos"] },
  { name: "Savannakhet", type: "city", country: "Laos", aliases: ["Savannakhet Laos"] },
  { name: "Luang Prabang", type: "city", country: "Laos", aliases: ["Luang Prabang Laos"] },
  { name: "Naypyidaw", type: "city", country: "Myanmar", aliases: ["Naypyidaw Myanmar"] },
  { name: "Yangon", type: "city", country: "Myanmar", aliases: ["Rangoon"] },
  { name: "Mandalay", type: "city", country: "Myanmar", aliases: ["Mandalay Myanmar"] },
  { name: "Mawlamyine", type: "city", country: "Myanmar", aliases: ["Moulmein"] },
  { name: "Bago", type: "city", country: "Myanmar", aliases: ["Pegu"] },
  { name: "Pathein", type: "city", country: "Myanmar", aliases: ["Bassein"] },
  { name: "Monywa", type: "city", country: "Myanmar", aliases: ["Monywa Myanmar"] },
  { name: "Meiktila", type: "city", country: "Myanmar", aliases: ["Meiktila Myanmar"] },
  { name: "Myitkyina", type: "city", country: "Myanmar", aliases: ["Myitkyina Myanmar"] },
  { name: "Sittwe", type: "city", country: "Myanmar", aliases: ["Akyab"] },
  { name: "Dhaka", type: "city", country: "Bangladesh", aliases: ["Dhaka Bangladesh"] },
  { name: "Chittagong", type: "city", country: "Bangladesh", aliases: ["Chattogram"] },
  { name: "Khulna", type: "city", country: "Bangladesh", aliases: ["Khulna Bangladesh"] },
  { name: "Rajshahi", type: "city", country: "Bangladesh", aliases: ["Rajshahi Bangladesh"] },
  { name: "Sylhet", type: "city", country: "Bangladesh", aliases: ["Sylhet Bangladesh"] },
  { name: "Rangpur", type: "city", country: "Bangladesh", aliases: ["Rangpur Bangladesh"] },
  { name: "Barisal", type: "city", country: "Bangladesh", aliases: ["Barisal Bangladesh"] },
  { name: "Comilla", type: "city", country: "Bangladesh", aliases: ["Comilla Bangladesh"] },
  { name: "Mymensingh", type: "city", country: "Bangladesh", aliases: ["Mymensingh Bangladesh"] },
  { name: "Gazipur", type: "city", country: "Bangladesh", aliases: ["Gazipur Bangladesh"] },
  { name: "Narayanganj", type: "city", country: "Bangladesh", aliases: ["Narayanganj Bangladesh"] },
  { name: "Savar", type: "city", country: "Bangladesh", aliases: ["Savar Bangladesh"] },
  { name: "Cox's Bazar", type: "city", country: "Bangladesh", aliases: ["Cox's Bazar Bangladesh"] },
  { name: "Jessore", type: "city", country: "Bangladesh", aliases: ["Jashore"] },
  { name: "Bogra", type: "city", country: "Bangladesh", aliases: ["Bogura"] },
  { name: "Dinajpur", type: "city", country: "Bangladesh", aliases: ["Dinajpur Bangladesh"] },
  { name: "Pabna", type: "city", country: "Bangladesh", aliases: ["Pabna Bangladesh"] },
  { name: "Tangail", type: "city", country: "Bangladesh", aliases: ["Tangail Bangladesh"] },
  { name: "Jamalpur", type: "city", country: "Bangladesh", aliases: ["Jamalpur Bangladesh"] },
  { name: "Kushtia", type: "city", country: "Bangladesh", aliases: ["Kushtia Bangladesh"] },
  { name: "Islamabad", type: "city", country: "Pakistan", aliases: ["Islamabad Pakistan"] },
  { name: "Karachi", type: "city", country: "Pakistan", aliases: ["Karachi Pakistan"] },
  { name: "Lahore", type: "city", country: "Pakistan", aliases: ["Lahore Pakistan"] },
  { name: "Faisalabad", type: "city", country: "Pakistan", aliases: ["Faisalabad Pakistan"] },
  { name: "Rawalpindi", type: "city", country: "Pakistan", aliases: ["Rawalpindi Pakistan"] },
  { name: "Gujranwala", type: "city", country: "Pakistan", aliases: ["Gujranwala Pakistan"] },
  { name: "Peshawar", type: "city", country: "Pakistan", aliases: ["Peshawar Pakistan"] },
  { name: "Multan", type: "city", country: "Pakistan", aliases: ["Multan Pakistan"] },
  { name: "Hyderabad", type: "city", country: "Pakistan", aliases: ["Hyderabad Pakistan"] },
  { name: "Quetta", type: "city", country: "Pakistan", aliases: ["Quetta Pakistan"] },
  { name: "Sargodha", type: "city", country: "Pakistan", aliases: ["Sargodha Pakistan"] },
  { name: "Sialkot", type: "city", country: "Pakistan", aliases: ["Sialkot Pakistan"] },
  { name: "Bahawalpur", type: "city", country: "Pakistan", aliases: ["Bahawalpur Pakistan"] },
  { name: "Sukkur", type: "city", country: "Pakistan", aliases: ["Sukkur Pakistan"] },
  { name: "Jhang", type: "city", country: "Pakistan", aliases: ["Jhang Pakistan"] },
  { name: "Sheikhupura", type: "city", country: "Pakistan", aliases: ["Sheikhupura Pakistan"] },
  { name: "Larkana", type: "city", country: "Pakistan", aliases: ["Larkana Pakistan"] },
  { name: "Gujrat", type: "city", country: "Pakistan", aliases: ["Gujrat Pakistan"] },
  { name: "Mardan", type: "city", country: "Pakistan", aliases: ["Mardan Pakistan"] },
  { name: "Kasur", type: "city", country: "Pakistan", aliases: ["Kasur Pakistan"] },
  { name: "Rahim Yar Khan", type: "city", country: "Pakistan", aliases: ["Rahim Yar Khan Pakistan"] },
  { name: "Sahiwal", type: "city", country: "Pakistan", aliases: ["Sahiwal Pakistan"] },
  { name: "Okara", type: "city", country: "Pakistan", aliases: ["Okara Pakistan"] },
  { name: "Wah Cantonment", type: "city", country: "Pakistan", aliases: ["Wah"] },
  { name: "Dera Ghazi Khan", type: "city", country: "Pakistan", aliases: ["DG Khan"] },
  { name: "Mirpur Khas", type: "city", country: "Pakistan", aliases: ["Mirpur Khas Pakistan"] },
  { name: "Nawabshah", type: "city", country: "Pakistan", aliases: ["Shaheed Benazirabad"] },
  { name: "Mingora", type: "city", country: "Pakistan", aliases: ["Mingora Pakistan"] },
  { name: "Chiniot", type: "city", country: "Pakistan", aliases: ["Chiniot Pakistan"] },
  { name: "Kamoke", type: "city", country: "Pakistan", aliases: ["Kamoke Pakistan"] },
  { name: "Mandi Bahauddin", type: "city", country: "Pakistan", aliases: ["Mandi Bahauddin Pakistan"] },
  { name: "Jhelum", type: "city", country: "Pakistan", aliases: ["Jhelum Pakistan"] },
  { name: "Sadiqabad", type: "city", country: "Pakistan", aliases: ["Sadiqabad Pakistan"] },
  { name: "Jacobabad", type: "city", country: "Pakistan", aliases: ["Jacobabad Pakistan"] },
  { name: "Shikarpur", type: "city", country: "Pakistan", aliases: ["Shikarpur Pakistan"] },
  { name: "Khanewal", type: "city", country: "Pakistan", aliases: ["Khanewal Pakistan"] },
  { name: "Hafizabad", type: "city", country: "Pakistan", aliases: ["Hafizabad Pakistan"] },
  { name: "Kohat", type: "city", country: "Pakistan", aliases: ["Kohat Pakistan"] },
  { name: "Muzaffargarh", type: "city", country: "Pakistan", aliases: ["Muzaffargarh Pakistan"] },
  { name: "Khanpur", type: "city", country: "Pakistan", aliases: ["Khanpur Pakistan"] },
  { name: "Gojra", type: "city", country: "Pakistan", aliases: ["Gojra Pakistan"] },
  { name: "Bahawalnagar", type: "city", country: "Pakistan", aliases: ["Bahawalnagar Pakistan"] },
  { name: "Muridke", type: "city", country: "Pakistan", aliases: ["Muridke Pakistan"] },
  { name: "Pak Pattan", type: "city", country: "Pakistan", aliases: ["Pakpattan"] },
  { name: "Abottabad", type: "city", country: "Pakistan", aliases: ["Abbottabad"] },
  { name: "Tando Adam", type: "city", country: "Pakistan", aliases: ["Tando Adam Pakistan"] },
  { name: "Jaranwala", type: "city", country: "Pakistan", aliases: ["Jaranwala Pakistan"] },
  { name: "Khairpur", type: "city", country: "Pakistan", aliases: ["Khairpur Pakistan"] },
  { name: "Chishtian Mandi", type: "city", country: "Pakistan", aliases: ["Chishtian"] },
  { name: "Daska", type: "city", country: "Pakistan", aliases: ["Daska Pakistan"] },
  { name: "Dadu", type: "city", country: "Pakistan", aliases: ["Dadu Pakistan"] },
  { name: "Mandi Burewala", type: "city", country: "Pakistan", aliases: ["Burewala"] },
  { name: "Chichawatni", type: "city", country: "Pakistan", aliases: ["Chichawatni Pakistan"] },
  { name: "Bannu", type: "city", country: "Pakistan", aliases: ["Bannu Pakistan"] },
  { name: "Balakot", type: "city", country: "Pakistan", aliases: ["Balakot Pakistan"] },
  { name: "Karak", type: "city", country: "Pakistan", aliases: ["Karak Pakistan"] },
  { name: "Hangu", type: "city", country: "Pakistan", aliases: ["Hangu Pakistan"] },
  { name: "Timergara", type: "city", country: "Pakistan", aliases: ["Timergara Pakistan"] },
  { name: "Charsadda", type: "city", country: "Pakistan", aliases: ["Charsadda Pakistan"] },
  { name: "Swabi", type: "city", country: "Pakistan", aliases: ["Swabi Pakistan"] },
  { name: "Dir", type: "city", country: "Pakistan", aliases: ["Dir Pakistan"] },
  { name: "Chitral", type: "city", country: "Pakistan", aliases: ["Chitral Pakistan"] },
  { name: "Landikotal", type: "city", country: "Pakistan", aliases: ["Landi Kotal"] },
  { name: "Parachinar", type: "city", country: "Pakistan", aliases: ["Parachinar Pakistan"] },
  { name: "Bannu", type: "city", country: "Pakistan", aliases: ["Bannu Pakistan"] },
  { name: "Kabul", type: "city", country: "Afghanistan", aliases: ["Kabul Afghanistan"] },
  { name: "Kandahar", type: "city", country: "Afghanistan", aliases: ["Kandahar Afghanistan"] },
  { name: "Herat", type: "city", country: "Afghanistan", aliases: ["Herat Afghanistan"] },
  { name: "Mazar-i-Sharif", type: "city", country: "Afghanistan", aliases: ["Mazar i Sharif"] },
  { name: "Kunduz", type: "city", country: "Afghanistan", aliases: ["Kunduz Afghanistan"] },
  { name: "Jalalabad", type: "city", country: "Afghanistan", aliases: ["Jalalabad Afghanistan"] },
  { name: "Lashkar Gah", type: "city", country: "Afghanistan", aliases: ["Lashkar Gah Afghanistan"] },
  { name: "Taloqan", type: "city", country: "Afghanistan", aliases: ["Taloqan Afghanistan"] },
  { name: "Sheberghan", type: "city", country: "Afghanistan", aliases: ["Sheberghan Afghanistan"] },
  { name: "Khost", type: "city", country: "Afghanistan", aliases: ["Khost Afghanistan"] },
  { name: "Gardez", type: "city", country: "Afghanistan", aliases: ["Gardez Afghanistan"] },
  { name: "Bamyan", type: "city", country: "Afghanistan", aliases: ["Bamyan Afghanistan"] },
  { name: "Ghazni", type: "city", country: "Afghanistan", aliases: ["Ghazni Afghanistan"] },
  { name: "Farah", type: "city", country: "Afghanistan", aliases: ["Farah Afghanistan"] },
  { name: "Zaranj", type: "city", country: "Afghanistan", aliases: ["Zaranj Afghanistan"] },
  { name: "Colombo", type: "city", country: "Sri Lanka", aliases: ["Colombo Sri Lanka"] },
  { name: "Dehiwala-Mount Lavinia", type: "city", country: "Sri Lanka", aliases: ["Dehiwala Mount Lavinia"] },
  { name: "Moratuwa", type: "city", country: "Sri Lanka", aliases: ["Moratuwa Sri Lanka"] },
  { name: "Negombo", type: "city", country: "Sri Lanka", aliases: ["Negombo Sri Lanka"] },
  { name: "Kandy", type: "city", country: "Sri Lanka", aliases: ["Kandy Sri Lanka"] },
  { name: "Kalmunai", type: "city", country: "Sri Lanka", aliases: ["Kalmunai Sri Lanka"] },
  { name: "Vavuniya", type: "city", country: "Sri Lanka", aliases: ["Vavuniya Sri Lanka"] },
  { name: "Galle", type: "city", country: "Sri Lanka", aliases: ["Galle Sri Lanka"] },
  { name: "Trincomalee", type: "city", country: "Sri Lanka", aliases: ["Trincomalee Sri Lanka"] },
  { name: "Batticaloa", type: "city", country: "Sri Lanka", aliases: ["Batticaloa Sri Lanka"] },
  { name: "Jaffna", type: "city", country: "Sri Lanka", aliases: ["Jaffna Sri Lanka"] },
  { name: "Kathmandu", type: "city", country: "Nepal", aliases: ["Kathmandu Nepal"] },
  { name: "Pokhara", type: "city", country: "Nepal", aliases: ["Pokhara Nepal"] },
  { name: "Lalitpur", type: "city", country: "Nepal", aliases: ["Patan"] },
  { name: "Bharatpur", type: "city", country: "Nepal", aliases: ["Bharatpur Nepal"] },
  { name: "Biratnagar", type: "city", country: "Nepal", aliases: ["Biratnagar Nepal"] },
  { name: "Birgunj", type: "city", country: "Nepal", aliases: ["Birgunj Nepal"] },
  { name: "Dharan", type: "city", country: "Nepal", aliases: ["Dharan Nepal"] },
  { name: "Hetauda", type: "city", country: "Nepal", aliases: ["Hetauda Nepal"] },
  { name: "Janakpur", type: "city", country: "Nepal", aliases: ["Janakpur Nepal"] },
  { name: "Butwal", type: "city", country: "Nepal", aliases: ["Butwal Nepal"] },
  { name: "Dhangadhi", type: "city", country: "Nepal", aliases: ["Dhangadhi Nepal"] },
  { name: "Mahendranagar", type: "city", country: "Nepal", aliases: ["Mahendranagar Nepal"] },
  { name: "Lahan", type: "city", country: "Nepal", aliases: ["Lahan Nepal"] },
  { name: "Siddharthanagar", type: "city", country: "Nepal", aliases: ["Bhairahawa"] },
  { name: "Bhadrapur", type: "city", country: "Nepal", aliases: ["Bhadrapur Nepal"] },
  { name: "Itahari", type: "city", country: "Nepal", aliases: ["Itahari Nepal"] },
  { name: "Dhankuta", type: "city", country: "Nepal", aliases: ["Dhankuta Nepal"] },
  { name: "Thimphu", type: "city", country: "Bhutan", aliases: ["Thimphu Bhutan"] },
  { name: "Phuntsholing", type: "city", country: "Bhutan", aliases: ["Phuentsholing"] },
  { name: "Punakha", type: "city", country: "Bhutan", aliases: ["Punakha Bhutan"] },
  { name: "Wangdue Phodrang", type: "city", country: "Bhutan", aliases: ["Wangdue Phodrang Bhutan"] },
  { name: "Samdrup Jongkhar", type: "city", country: "Bhutan", aliases: ["Samdrup Jongkhar Bhutan"] },
  { name: "Gelephu", type: "city", country: "Bhutan", aliases: ["Gelephu Bhutan"] },
  { name: "Male", type: "city", country: "Maldives", aliases: ["Male Maldives"] },
  { name: "Addu City", type: "city", country: "Maldives", aliases: ["Addu"] },
  { name: "Fuvahmulah", type: "city", country: "Maldives", aliases: ["Fuvahmulah Maldives"] },
  { name: "Kulhudhuffushi", type: "city", country: "Maldives", aliases: ["Kulhudhuffushi Maldives"] },
  { name: "Thinadhoo", type: "city", country: "Maldives", aliases: ["Thinadhoo Maldives"] },
  { name: "Ungoofaaru", type: "city", country: "Maldives", aliases: ["Ungoofaaru Maldives"] },
  { name: "Naifaru", type: "city", country: "Maldives", aliases: ["Naifaru Maldives"] },
  { name: "Hithadhoo", type: "city", country: "Maldives", aliases: ["Hithadhoo Maldives"] },

  // European Cities
  { name: "Vienna", type: "city", country: "Austria", aliases: ["Wien"] },
  { name: "Graz", type: "city", country: "Austria", aliases: ["Graz Austria"] },
  { name: "Linz", type: "city", country: "Austria", aliases: ["Linz Austria"] },
  { name: "Salzburg", type: "city", country: "Austria", aliases: ["Salzburg Austria"] },
  { name: "Innsbruck", type: "city", country: "Austria", aliases: ["Innsbruck Austria"] },
  { name: "Klagenfurt", type: "city", country: "Austria", aliases: ["Klagenfurt Austria"] },
  { name: "Villach", type: "city", country: "Austria", aliases: ["Villach Austria"] },
  { name: "Wels", type: "city", country: "Austria", aliases: ["Wels Austria"] },
  { name: "St. Pölten", type: "city", country: "Austria", aliases: ["Sankt Polten"] },
  { name: "Dornbirn", type: "city", country: "Austria", aliases: ["Dornbirn Austria"] },
  { name: "Wiener Neustadt", type: "city", country: "Austria", aliases: ["Wiener Neustadt Austria"] },
  { name: "Steyr", type: "city", country: "Austria", aliases: ["Steyr Austria"] },
  { name: "Feldkirch", type: "city", country: "Austria", aliases: ["Feldkirch Austria"] },
  { name: "Bregenz", type: "city", country: "Austria", aliases: ["Bregenz Austria"] },
  { name: "Leonding", type: "city", country: "Austria", aliases: ["Leonding Austria"] },
  { name: "Klosterneuburg", type: "city", country: "Austria", aliases: ["Klosterneuburg Austria"] },
  { name: "Baden", type: "city", country: "Austria", aliases: ["Baden Austria"] },
  { name: "Wolfsberg", type: "city", country: "Austria", aliases: ["Wolfsberg Austria"] },
  { name: "Leoben", type: "city", country: "Austria", aliases: ["Leoben Austria"] },
  { name: "Krems", type: "city", country: "Austria", aliases: ["Krems Austria"] },
  { name: "Brussels", type: "city", country: "Belgium", aliases: ["Bruxelles", "Brussel"] },
  { name: "Antwerp", type: "city", country: "Belgium", aliases: ["Antwerpen"] },
  { name: "Ghent", type: "city", country: "Belgium", aliases: ["Gent"] },
  { name: "Charleroi", type: "city", country: "Belgium", aliases: ["Charleroi Belgium"] },
  { name: "Liège", type: "city", country: "Belgium", aliases: ["Liege"] },
  { name: "Bruges", type: "city", country: "Belgium", aliases: ["Brugge"] },
  { name: "Namur", type: "city", country: "Belgium", aliases: ["Namen"] },
  { name: "Leuven", type: "city", country: "Belgium", aliases: ["Louvain"] },
  { name: "Mons", type: "city", country: "Belgium", aliases: ["Bergen"] },
  { name: "Aalst", type: "city", country: "Belgium", aliases: ["Alost"] },
  { name: "La Louvière", type: "city", country: "Belgium", aliases: ["La Louviere Belgium"] },
  { name: "Kortrijk", type: "city", country: "Belgium", aliases: ["Courtrai"] },
  { name: "Hasselt", type: "city", country: "Belgium", aliases: ["Hasselt Belgium"] },
  { name: "Sint-Niklaas", type: "city", country: "Belgium", aliases: ["Saint Nicolas"] },
  { name: "Ostend", type: "city", country: "Belgium", aliases: ["Oostende"] },
  { name: "Genk", type: "city", country: "Belgium", aliases: ["Genk Belgium"] },
  { name: "Seraing", type: "city", country: "Belgium", aliases: ["Seraing Belgium"] },
  { name: "Roeselare", type: "city", country: "Belgium", aliases: ["Roulers"] },
  { name: "Verviers", type: "city", country: "Belgium", aliases: ["Verviers Belgium"] },
  { name: "Dendermonde", type: "city", country: "Belgium", aliases: ["Termonde"] },

  // Major Airports (important for cargo)
  { name: "Frankfurt", type: "airport", country: "Germany", aliases: ["Frankfurt Airport", "FRA", "Frankfurt am Main"] },
  { name: "Memphis Airport", type: "airport", country: "USA", aliases: ["MEM", "FedEx Hub"] },
  { name: "Louisville", type: "airport", country: "USA", aliases: ["Louisville Airport", "SDF", "UPS Hub"] },
  { name: "Anchorage", type: "airport", country: "USA", aliases: ["Anchorage Airport", "ANC"] },
  { name: "Paris Charles de Gaulle", type: "airport", country: "France", aliases: ["CDG", "Roissy"] },
  { name: "Amsterdam Schiphol", type: "airport", country: "Netherlands", aliases: ["AMS", "Schiphol"] },
  { name: "Hong Kong Airport", type: "airport", country: "Hong Kong", aliases: ["HKG", "Chek Lap Kok"] },
  { name: "Incheon", type: "airport", country: "South Korea", aliases: ["ICN", "Seoul Airport"] },
  { name: "Dubai Airport", type: "airport", country: "UAE", aliases: ["DXB"] },
  { name: "Doha", type: "airport", country: "Qatar", aliases: ["DOH", "Hamad Airport"] },

  // Logistics Hubs & Warehouses
  { name: "Joliet", type: "logistics_hub", country: "USA", aliases: ["Joliet IL", "CenterPoint Joliet"] },
  { name: "Edison", type: "logistics_hub", country: "USA", aliases: ["Edison NJ"] },
  { name: "Riverside", type: "logistics_hub", country: "USA", aliases: ["Riverside CA", "Inland Empire"] },
  { name: "Ontario", type: "logistics_hub", country: "USA", aliases: ["Ontario CA"] },
  { name: "Laredo", type: "logistics_hub", country: "USA", aliases: ["Laredo TX"] },
  { name: "El Paso", type: "logistics_hub", country: "USA", aliases: ["El Paso TX"] },
  { name: "Brownsville", type: "logistics_hub", country: "USA", aliases: ["Brownsville TX"] },
  { name: "Nogales", type: "logistics_hub", country: "USA", aliases: ["Nogales AZ"] },
  { name: "Duisburg", type: "logistics_hub", country: "Germany", aliases: ["Duisburg Port"] },
  { name: "Venlo", type: "logistics_hub", country: "Netherlands", aliases: ["Venlo Logistics"] },
  { name: "Zaragoza", type: "logistics_hub", country: "Spain", aliases: ["Zaragoza Logistics"] },

  // Additional Strategic Locations
  { name: "Suez Canal", type: "logistics_hub", country: "Egypt", aliases: ["Suez", "Port Said"] },
  { name: "Panama Canal", type: "logistics_hub", country: "Panama", aliases: ["Panama", "Colon"] },
  { name: "Strait of Malacca", type: "logistics_hub", country: "Malaysia", aliases: ["Malacca", "Port Klang"] },
  { name: "Gibraltar", type: "logistics_hub", country: "Gibraltar", aliases: ["Strait of Gibraltar"] },
];

/**
 * Search locations based on query string
 */
export function searchLocations(query: string, limit: number = 10): Location[] {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  // First, find exact matches and prefix matches
  const exactMatches = LOCATIONS_DATABASE.filter(location => 
    location.name.toLowerCase().startsWith(normalizedQuery)
  );
  
  // Then find matches in aliases
  const aliasMatches = LOCATIONS_DATABASE.filter(location => 
    !exactMatches.includes(location) && 
    location.aliases?.some(alias => alias.toLowerCase().includes(normalizedQuery))
  );
  
  // Finally, find partial matches in names
  const partialMatches = LOCATIONS_DATABASE.filter(location => 
    !exactMatches.includes(location) && 
    !aliasMatches.includes(location) &&
    location.name.toLowerCase().includes(normalizedQuery)
  );
  
  // Combine results with priority: exact matches first, then alias matches, then partial matches
  const results = [...exactMatches, ...aliasMatches, ...partialMatches];
  
  return results.slice(0, limit);
}

/**
 * Get location by exact name match
 */
export function getLocationByName(name: string): Location | null {
  const normalizedName = name.toLowerCase().trim();
  
  return LOCATIONS_DATABASE.find(location => 
    location.name.toLowerCase() === normalizedName ||
    location.aliases?.some(alias => alias.toLowerCase() === normalizedName)
  ) || null;
}

/**
 * Get all locations of a specific type
 */
export function getLocationsByType(type: Location['type']): Location[] {
  return LOCATIONS_DATABASE.filter(location => location.type === type);
}

/**
 * Get locations by country
 */
export function getLocationsByCountry(country: string): Location[] {
  const normalizedCountry = country.toLowerCase().trim();
  return LOCATIONS_DATABASE.filter(location => 
    location.country.toLowerCase() === normalizedCountry
  );
}
